apiVersion: v1
kind: Service
metadata:
  name: terraform-operator-metrics
  labels:
    app: terraform-operator
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: terraform-operator-metrics
  labels:
    app: terraform-operator
subsets:
- addresses:
  - ip: "192.168.65.2"
  ports: 
  - name: metrics
    port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: terraform-operator-metrics
  labels:
    app: terraform-operator
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: terraform-operator