apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
  name: terraform-sample
spec:
  terraformVersion: 1.0.2

  module:
    source: IbraheemAlSaady/test/module//modules/aws
    version: 0.0.2

  variables:
    - key: name
      value: "my bucket"
    - key: AWS_DEFAULT_REGION
      value: eu-west-1
      environmentVariable: true
      value: "my bucket"
    - key: AWS_ACCESS_KEY_ID
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - key: AWS_SECRET_ACCESS_KEY
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID

  backend: |
    backend "local" {
      path = "/tmp/tfmodule/mytfstate.tfstate"
    }

  # workspace: dev

  destroy: false
  deleteCompletedJobs: false

  # retryLimit: 1
  
  # workspace: prod

  # dependsOn: []

  # variables:
  #   - key: AWS_ACCESS_KEY
  #     value: "ajwdhh1239ianwdjabwd"
  #     environmentVariable: true
    # - key: length
    #   sensitive: false
    #   valueFrom:
    #     secretKeyRef:
    #       name: tfrun
    #       key: length

  # outputs:
  #   - key: my_output
  #     moduleOutputName: result
  #     sensitive: false
