apiVersion: run.terraform-operator.io/v1alpha1
kind: Terraform
metadata:
  name: terraform-az-storage
spec:
  terraformVersion: 1.0.2

  module:
    source: IbraheemAlSaady/test/module//modules/azure
    version: 0.0.2

  variables:
    - key: name
      value: "mystorage"
    - key: ARM_CLIENT_ID
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: azure-credentials
          key: ARM_CLIENT_ID
    - key: ARM_CLIENT_SECRET
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: azure-credentials
          key: ARM_CLIENT_SECRET
    - key: ARM_SUBSCRIPTION_ID
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: azure-credentials
          key: ARM_SUBSCRIPTION_ID
    - key: ARM_TENANT_ID
      environmentVariable: true
      valueFrom:
        secretKeyRef:
          name: azure-credentials
          key: ARM_TENANT_ID

  backend: |
    backend "local" {
      path = "/tmp/tfmodule/mytfstate.tfstate"
    }
  
  providersConfig: |
    terraform {
      required_providers {
        azurerm = {
          source  = "hashicorp/azurerm"
          version = "=2.46.0"
        }
      }
    }

    provider "azurerm" {
      features {}
    }

  # workspace: dev

  destroy: false
  deleteCompletedJobs: false

  retryLimit: 1
  
  outputs:
    - key: storage_account_id
      moduleOutputName: id 
      sensitive: false
