name: Pull Request

on:
  pull_request:
    branches:
      - main
      - master
      - 'releases/**'
      - 'feature/**'
      - 'fix/**'
  push:
    branches-ignore:
      - master
      - main
      - 'releases/**'
    tags-ignore:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make build

    - name: Test
      run: make docker-build